package front;


import equipmentrent.ConnDB;
import equipmentrent.Damage;
import equipmentrent.Equipment;
import equipmentrent.User;
import java.awt.Component;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.SwingUtilities;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Salman
 */
public class RentJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RentJPanel
     */
    User user;
    Equipment selectedEquipment;
    Equipment[] avalibleEquipments;

    public RentJPanel(User passedUser) {
        initComponents();
        user = passedUser;
        damageList.setEnabled(false);
        rentButton.setEnabled(false);
        avalibleEquipments = new ConnDB().getAvailableEquipment();

        String[] equipmentsNames = new String[avalibleEquipments.length];
        for (int i = 0; i < avalibleEquipments.length; i++) {
            System.out.println(avalibleEquipments[i].name);
            equipmentsNames[i] = avalibleEquipments[i].name;
        }
        
        keyScanner.requestFocus();

        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        damageList = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        modelLabel = new javax.swing.JLabel();
        idLabel = new javax.swing.JLabel();
        levelLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        damgeTextArea = new javax.swing.JTextArea();
        rentButton = new javax.swing.JButton();
        keyScanner = new javax.swing.JTextField();
        scannFoucsButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 204));
        setMinimumSize(new java.awt.Dimension(100, 100));

        damageList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                damageListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(damageList);

        jLabel1.setFont(new java.awt.Font("Traditional Arabic", 1, 24)); // NOI18N
        jLabel1.setText("الموديل");

        jLabel2.setFont(new java.awt.Font("Traditional Arabic", 1, 24)); // NOI18N
        jLabel2.setText("الاسم:");

        jLabel3.setFont(new java.awt.Font("Traditional Arabic", 1, 24)); // NOI18N
        jLabel3.setText("المستوى");

        jLabel4.setFont(new java.awt.Font("Traditional Arabic", 1, 24)); // NOI18N
        jLabel4.setText("ID");

        nameLabel.setFont(new java.awt.Font("Traditional Arabic", 1, 24)); // NOI18N

        modelLabel.setFont(new java.awt.Font("Traditional Arabic", 1, 24)); // NOI18N

        idLabel.setFont(new java.awt.Font("Traditional Arabic", 1, 24)); // NOI18N

        levelLabel.setFont(new java.awt.Font("Traditional Arabic", 1, 24)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Traditional Arabic", 1, 24)); // NOI18N
        jLabel6.setText("وصف الضرر");

        damgeTextArea.setColumns(20);
        damgeTextArea.setRows(5);
        jScrollPane3.setViewportView(damgeTextArea);

        rentButton.setText("استعر");
        rentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentButtonActionPerformed(evt);
            }
        });

        keyScanner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keyScannerActionPerformed(evt);
            }
        });
        keyScanner.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                keyScannerKeyTyped(evt);
            }
        });

        scannFoucsButton.setText("اضغطني لعمل المسح");
        scannFoucsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scannFoucsButtonActionPerformed(evt);
            }
        });

        jButton1.setText("عودة");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(608, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(keyScanner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addGap(11, 11, 11)
                        .addComponent(scannFoucsButton)
                        .addGap(8, 8, 8)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(modelLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nameLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(levelLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(idLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(rentButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)))
                .addGap(227, 227, 227))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nameLabel)
                        .addGap(40, 40, 40)
                        .addComponent(modelLabel)
                        .addGap(40, 40, 40)
                        .addComponent(idLabel)
                        .addGap(40, 40, 40)
                        .addComponent(levelLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel1)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel4)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rentButton)
                            .addComponent(keyScanner, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(scannFoucsButton)
                            .addComponent(jButton1))))
                .addGap(0, 4, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void damageListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_damageListMouseClicked

        Damage damge = selectedEquipment.damges[damageList.getSelectedIndex()];

        damgeTextArea.setText(damge.description);

    }//GEN-LAST:event_damageListMouseClicked

    private void rentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentButtonActionPerformed
        JOptionPane.showMessageDialog(this, "عند استعارتك انت تؤكد انك اطلعت على الأضرار السابقة وستتحمل مسؤلية اي ضرر اضافي");

        user.rent(selectedEquipment);

        JFrame mainFram = (JFrame) SwingUtilities.getWindowAncestor(this);

        mainFram.setContentPane(new RentJPanel(user));
        mainFram.invalidate();
        mainFram.validate();
    }//GEN-LAST:event_rentButtonActionPerformed

    private void keyScannerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keyScannerActionPerformed
        selectedEquipment = Equipment.getEquipment(Integer.valueOf(keyScanner.getText()));
        if (selectedEquipment != null) {
            damageList.setEnabled(true);
            rentButton.setEnabled(true);
            nameLabel.setText(selectedEquipment.name);
            modelLabel.setText(selectedEquipment.model);
            levelLabel.setText("" + selectedEquipment.level);
            idLabel.setText("" + selectedEquipment.id);

            String[] damgeNames = new String[selectedEquipment.damges.length];
            for (int i = 0; i < selectedEquipment.damges.length; i++) {
                damgeNames[i] = "الضرر " + i;
            }

            damageList.setModel(
                    new javax.swing.AbstractListModel<String>() {
                String[] strings = damgeNames;

                @Override
                public int getSize() {
                    return strings.length;
                }

                @Override
                public String getElementAt(int i) {
                    return strings[i];
                }
            }
            );

        } else {
            JOptionPane.showMessageDialog(this, "مفتاح خطأ , امسح مرة اخرى");
            keyScanner.requestFocus();
            keyScanner.setText("");
        }
    }//GEN-LAST:event_keyScannerActionPerformed

    private void keyScannerKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_keyScannerKeyTyped

    }//GEN-LAST:event_keyScannerKeyTyped

    private void scannFoucsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scannFoucsButtonActionPerformed
        keyScanner.requestFocus();
    }//GEN-LAST:event_scannFoucsButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFrame mainFram = (JFrame) SwingUtilities.getWindowAncestor(this);

        mainFram.setContentPane(new UserJPanel(user));
        mainFram.invalidate();
        mainFram.validate();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> damageList;
    private javax.swing.JTextArea damgeTextArea;
    private javax.swing.JLabel idLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField keyScanner;
    private javax.swing.JLabel levelLabel;
    private javax.swing.JLabel modelLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JButton rentButton;
    private javax.swing.JButton scannFoucsButton;
    // End of variables declaration//GEN-END:variables
}
